# Stage 1: Build the JAR
FROM gradle:8.4-jdk17 AS builder

# Stage 2: Run the application
FROM openjdk:17-jdk-slim


# Create a working directory
WORKDIR /app

# Copy everything and build the app
COPY --chown=gradle:gradle . .
RUN gradle build --no-daemon

# Copy the JAR file into the image
COPY --from=builder /app/build/libs/bitespeed-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "app.jar"]
