# -------- Build stage --------
FROM eclipse-temurin:17-jdk-jammy as builder

WORKDIR /app
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew build --no-daemon

# -------- Runtime stage --------
FROM eclipse-temurin:17-jre-jammy

# Copy the JAR file from the builder stage
COPY --from=builder /app/build/libs/bitespeed-0.0.1-SNAPSHOT.jar app.jar

# Expose port if your app listens on a port (e.g., 8080)
EXPOSE 8080

# Run the jar
ENTRYPOINT ["java", "-jar", "/app.jar"]