# Use OpenJDK as base image
FROM openjdk:17-jdk-slim

# Create a working directory
WORKDIR /app

# Copy the JAR file into the image
COPY build/libs/bitespeed-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
